/** Тема сертификатов: шрифты (Noto Sans, кириллица), палитра сайта, размеры A4, общий StyleSheet всех макетов, слоган по умолчанию. */
import path from 'path';
import { existsSync } from 'fs';
import { StyleSheet, Font } from '@react-pdf/renderer';
import type { CertificateData } from './types';

export const notoSans400 = path.join(
  process.cwd(),
  'node_modules',
  '@fontsource',
  'noto-sans',
  'files',
  'noto-sans-cyrillic-400-normal.woff'
);
export const notoSans600 = path.join(
  process.cwd(),
  'node_modules',
  '@fontsource',
  'noto-sans',
  'files',
  'noto-sans-cyrillic-600-normal.woff'
);

export let FONT_FAMILY_FALLBACK = 'Helvetica';
if (existsSync(notoSans400)) {
  try {
    const fonts: { src: string; fontWeight: number }[] = [{ src: notoSans400, fontWeight: 400 }];
    if (existsSync(notoSans600)) fonts.push({ src: notoSans600, fontWeight: 600 });
    Font.register({ family: 'NotoSans', fonts });
    FONT_FAMILY_FALLBACK = 'NotoSans';
  } catch {
    // Helvetica
  }
}

/** Согласовано с лендингом: --plum, --rose, --lavender-light, --periwinkle, --text */
export const COLORS = {
  primary: '#856b92',
  primaryDark: '#6d5679',
  secondary: '#ce8fb0',
  dark: '#1e293b',
  cream: '#faf9fc',
  parchment: '#f4f2f8',
  white: '#ffffff',
  muted: '#64748b',
  goldSoft: '#b4b1d8',
  roseWash: '#fdf5f9',
  /** Обводки в тон золотому логотипу (без заливки фона листа). */
  certGold: '#a67c52',
  certGoldLight: '#c9a86c',
  /** Как ссылки на блоге / витрине: акцент на белом фоне. */
  linkAccent: '#2d5aa1',
  /** Тёплое золото круга логотипа (скрин блога). */
  blogGold: '#c4a060',
  blogGoldDeep: '#8a6a3f',
  blogCream: '#fffdf8',
} as const;

/** A4 в пунктах @react-pdf/renderer — подложки Image и SVG одного размера */
export const PDF_PAGE_W = 595.28;
export const PDF_PAGE_H = 841.89;

/** Витринные фоны (копируются в репозиторий из дизайна); при отсутствии файла — SVG-запасной вариант */
export const SHOWCASE_CERT_BG = {
  vitality: path.join(process.cwd(), 'public', 'images', 'certificates', 'bg-vitality.png'),
  awaken: path.join(process.cwd(), 'public', 'images', 'certificates', 'bg-awaken.png'),
  path: path.join(process.cwd(), 'public', 'images', 'certificates', 'bg-path.png'),
} as const;

export const FONT_FAMILY = FONT_FAMILY_FALLBACK;

export const styles = StyleSheet.create({
  page: {
    padding: 0,
    fontFamily: FONT_FAMILY,
    backgroundColor: COLORS.white,
  },
  pageCream: {
    padding: 0,
    fontFamily: FONT_FAMILY,
    backgroundColor: COLORS.white,
  },
  // —— Классика (default / heritage) ——
  heritagePage: {
    backgroundColor: COLORS.white,
    fontFamily: FONT_FAMILY,
    padding: 0,
  },
  heritageOuterFrame: {
    position: 'absolute',
    top: 24,
    left: 24,
    right: 24,
    bottom: 24,
    borderWidth: 2,
    borderColor: COLORS.certGold,
    borderRadius: 3,
  },
  heritageMidFrame: {
    position: 'absolute',
    top: 32,
    left: 32,
    right: 32,
    bottom: 32,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 2,
    opacity: 0.85,
  },
  heritageInnerFrame: {
    position: 'absolute',
    top: 40,
    left: 40,
    right: 40,
    bottom: 40,
    borderWidth: 0.75,
    borderColor: COLORS.goldSoft,
    borderRadius: 1,
  },
  heritageCornerTL: {
    position: 'absolute',
    top: 44,
    left: 44,
    width: 36,
    height: 36,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderColor: COLORS.primary,
  },
  heritageCornerTR: {
    position: 'absolute',
    top: 44,
    right: 44,
    width: 36,
    height: 36,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderColor: COLORS.certGold,
  },
  heritageCornerBL: {
    position: 'absolute',
    bottom: 44,
    left: 44,
    width: 36,
    height: 36,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderColor: COLORS.certGold,
  },
  heritageCornerBR: {
    position: 'absolute',
    bottom: 44,
    right: 44,
    width: 36,
    height: 36,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderColor: COLORS.primary,
  },
  heritageBody: {
    flex: 1,
    paddingHorizontal: 48,
    paddingTop: 44,
    paddingBottom: 32,
    alignItems: 'center',
  },
  heritageLogo: {
    width: 200,
    height: 64,
    objectFit: 'contain',
    marginBottom: 10,
  },
  heritageWordmark: {
    fontSize: 22,
    fontWeight: 600,
    color: COLORS.primary,
    letterSpacing: 3,
    marginBottom: 6,
  },
  heritageTagline: {
    fontSize: 9,
    color: COLORS.muted,
    letterSpacing: 0.5,
    marginBottom: 18,
    textAlign: 'center',
  },
  heritageCertLabel: {
    fontSize: 11,
    color: COLORS.certGold,
    letterSpacing: 5,
    marginBottom: 6,
  },
  heritageTitle: {
    fontSize: 26,
    fontWeight: 600,
    color: COLORS.primary,
    letterSpacing: 2,
    marginBottom: 10,
  },
  heritageHairline: {
    width: 168,
    height: 0,
    borderBottomWidth: 2,
    borderBottomColor: COLORS.certGold,
    marginBottom: 22,
  },
  heritageLead: {
    fontSize: 11,
    color: COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
  },
  heritageName: {
    fontSize: 24,
    fontWeight: 600,
    color: COLORS.dark,
    textAlign: 'center',
    marginBottom: 14,
    maxWidth: 480,
  },
  heritageCourseHint: {
    fontSize: 11,
    color: COLORS.muted,
    marginBottom: 6,
    textAlign: 'center',
  },
  heritageCourse: {
    fontSize: 17,
    fontWeight: 600,
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 8,
    maxWidth: 480,
  },
  heritageGrow: {
    flexGrow: 1,
    minHeight: 8,
  },
  heritageFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 420,
    borderTopWidth: 1,
    borderTopColor: COLORS.goldSoft,
    paddingTop: 14,
    marginTop: 8,
  },
  heritageMeta: {
    fontSize: 9,
    color: COLORS.muted,
  },
  heritageExpiry: {
    fontSize: 9,
    color: COLORS.primary,
    marginTop: 10,
    textAlign: 'center',
  },
  heritageSite: {
    fontSize: 8,
    color: COLORS.secondary,
    marginTop: 10,
    letterSpacing: 1,
  },
  heritageFlourishWrap: {
    alignItems: 'center',
    marginBottom: 4,
  },
  heritageMicroLine: {
    fontSize: 7,
    color: COLORS.muted,
    textAlign: 'center',
    marginTop: 4,
    letterSpacing: 0.3,
  },
  heritageFinePrint: {
    fontSize: 7,
    color: COLORS.muted,
    textAlign: 'center',
    marginTop: 6,
    maxWidth: 420,
    lineHeight: 1.35,
  },
  heritageAwardBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 6,
  },
  heritageSealOuter: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 2,
    borderColor: COLORS.certGold,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  heritageSealInner: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 0.75,
    borderColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heritageSealCaption: {
    maxWidth: 210,
    marginLeft: 14,
  },
  heritageSealCapTitle: {
    fontSize: 8,
    fontWeight: 600,
    color: COLORS.primary,
    letterSpacing: 0.8,
  },
  heritageSealCapSub: {
    fontSize: 7,
    color: COLORS.muted,
    marginTop: 2,
  },
  heritageSignaturesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 400,
    marginTop: 12,
    paddingTop: 8,
  },
  heritageSigCol: {
    width: '42%',
    alignItems: 'center',
  },
  heritageSigLine: {
    fontSize: 9,
    color: COLORS.goldSoft,
    marginBottom: 4,
    letterSpacing: 1,
  },
  heritageSigCap: {
    fontSize: 7,
    color: COLORS.muted,
    textAlign: 'center',
  },
  heritageSideDotsLeft: {
    position: 'absolute',
    left: 14,
    top: 248,
    flexDirection: 'column',
  },
  heritageSideDotsRight: {
    position: 'absolute',
    right: 14,
    top: 248,
    flexDirection: 'column',
  },
  heritageDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    borderWidth: 0.75,
    borderColor: COLORS.certGold,
    opacity: 0.55,
    marginBottom: 6,
  },
  // —— Премиум (prestige) ——
  prestigeHeader: {
    backgroundColor: 'transparent',
    borderBottomWidth: 2,
    borderBottomColor: COLORS.certGold,
    paddingVertical: 20,
    paddingHorizontal: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  prestigeHeaderLogo: {
    width: 132,
    height: 52,
    objectFit: 'contain',
  },
  prestigeHeaderWordmark: {
    fontSize: 16,
    fontWeight: 600,
    color: COLORS.primaryDark,
    letterSpacing: 2,
  },
  prestigeHeaderRight: {
    alignItems: 'flex-end',
  },
  prestigeHeaderCaption: {
    fontSize: 8,
    color: COLORS.secondary,
    letterSpacing: 1.5,
    marginBottom: 2,
  },
  prestigeHeaderTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: COLORS.primaryDark,
    letterSpacing: 2,
  },
  prestigeGoldBar: {
    height: 0,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.certGoldLight,
    opacity: 0.9,
  },
  prestigeBodyWrap: {
    position: 'relative',
    flex: 1,
    marginHorizontal: 26,
    marginTop: 26,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: COLORS.certGold,
    borderRadius: 4,
    paddingHorizontal: 36,
    paddingTop: 44,
    paddingBottom: 28,
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  prestigeInnerAccent: {
    position: 'absolute',
    top: 34,
    left: 34,
    right: 34,
    bottom: 34,
    borderWidth: 0.5,
    borderColor: COLORS.primary,
    opacity: 0.25,
  },
  prestigeDecorTop: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1.5,
    borderColor: COLORS.certGold,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  prestigeDecorInner: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    borderWidth: 1.25,
    borderColor: COLORS.certGoldLight,
    backgroundColor: COLORS.white,
  },
  prestigeLead: {
    fontSize: 10,
    color: COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 12,
  },
  prestigeName: {
    fontSize: 22,
    fontWeight: 600,
    color: COLORS.dark,
    textAlign: 'center',
    marginBottom: 12,
    maxWidth: 460,
  },
  prestigeCourseLine: {
    fontSize: 11,
    color: COLORS.muted,
    marginBottom: 6,
    textAlign: 'center',
  },
  prestigeCourse: {
    fontSize: 16,
    fontWeight: 600,
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 16,
    maxWidth: 460,
  },
  prestigeGrow: {
    flexGrow: 1,
    minHeight: 20,
  },
  prestigeFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 400,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.certGold,
  },
  prestigeMeta: {
    fontSize: 9,
    color: COLORS.muted,
  },
  prestigeExpiry: {
    fontSize: 9,
    color: COLORS.primary,
    marginTop: 12,
    textAlign: 'center',
  },
  prestigeBottomBar: {
    backgroundColor: COLORS.white,
    borderTopWidth: 2,
    borderTopColor: COLORS.certGold,
    paddingVertical: 12,
    paddingHorizontal: 40,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  prestigeSite: {
    fontSize: 8,
    color: COLORS.muted,
    letterSpacing: 1,
  },
  prestigeQuote: {
    fontSize: 8,
    fontStyle: 'normal',
    color: COLORS.muted,
    textAlign: 'center',
    marginTop: 10,
    maxWidth: 400,
    lineHeight: 1.45,
  },
  prestigeBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 12,
  },
  prestigeBadge: {
    borderWidth: 1,
    borderColor: COLORS.goldSoft,
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 10,
    backgroundColor: COLORS.white,
    marginHorizontal: 4,
    marginBottom: 4,
  },
  prestigeBadgeText: {
    fontSize: 7,
    color: COLORS.primary,
    fontWeight: 600,
  },
  prestigeSideAccentLeft: {
    position: 'absolute',
    left: 10,
    top: 130,
    width: 0,
    height: 300,
    borderLeftWidth: 1.25,
    borderLeftColor: COLORS.certGold,
    opacity: 0.55,
  },
  prestigeSideAccentRight: {
    position: 'absolute',
    right: 10,
    top: 130,
    width: 0,
    height: 300,
    borderRightWidth: 1.25,
    borderRightColor: COLORS.primary,
    opacity: 0.35,
  },
  // —— minimal ——
  minimalWrap: {
    padding: 56,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  minimalLogo: {
    width: 128,
    height: 52,
    objectFit: 'contain',
    marginBottom: 12,
  },
  minimalTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: COLORS.primary,
    letterSpacing: 2,
    marginBottom: 6,
  },
  minimalSubtitle: {
    fontSize: 10,
    color: COLORS.muted,
    marginBottom: 32,
    textAlign: 'center',
  },
  minimalName: {
    fontSize: 24,
    fontWeight: 600,
    color: COLORS.dark,
    marginBottom: 12,
    textAlign: 'center',
  },
  minimalCourse: {
    fontSize: 14,
    color: COLORS.primary,
    marginBottom: 28,
    textAlign: 'center',
  },
  minimalDivider: {
    width: 96,
    height: 0,
    borderBottomWidth: 2,
    borderBottomColor: COLORS.certGold,
    marginBottom: 24,
  },
  minimalMeta: {
    fontSize: 10,
    color: COLORS.muted,
    textAlign: 'center',
  },
  minimalExpiry: {
    fontSize: 9,
    color: COLORS.primary,
    marginTop: 8,
    textAlign: 'center',
  },
  minimalOuterGlow: {
    position: 'absolute',
    top: 26,
    left: 26,
    right: 26,
    bottom: 26,
    borderWidth: 1,
    borderColor: COLORS.secondary,
    borderRadius: 10,
    opacity: 0.4,
  },
  minimalCornerTL: {
    position: 'absolute',
    top: 38,
    left: 38,
    width: 56,
    height: 56,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderColor: COLORS.secondary,
    opacity: 0.5,
    borderRadius: 2,
  },
  minimalCornerBR: {
    position: 'absolute',
    bottom: 38,
    right: 38,
    width: 56,
    height: 56,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderColor: COLORS.primary,
    opacity: 0.4,
    borderRadius: 2,
  },
  minimalKicker: {
    fontSize: 8,
    letterSpacing: 3,
    color: COLORS.secondary,
    marginBottom: 10,
    fontWeight: 600,
  },
  minimalFlourish: {
    marginBottom: 14,
    alignItems: 'center',
  },
  minimalSchoolLine: {
    fontSize: 9,
    color: COLORS.muted,
    textAlign: 'center',
    marginTop: 24,
    maxWidth: 340,
    lineHeight: 1.45,
  },
  // —— elegant ——
  elegantBorder: {
    position: 'absolute',
    top: 32,
    left: 32,
    right: 32,
    bottom: 32,
    borderWidth: 2,
    borderColor: COLORS.certGold,
    borderRadius: 4,
  },
  elegantInner: {
    position: 'absolute',
    top: 40,
    left: 40,
    right: 40,
    bottom: 40,
    borderWidth: 1,
    borderColor: COLORS.primary,
    opacity: 0.4,
    borderRadius: 2,
  },
  elegantContent: {
    padding: 72,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  elegantLogo: {
    width: 140,
    height: 52,
    objectFit: 'contain',
    marginBottom: 14,
  },
  elegantTitle: {
    fontSize: 22,
    fontWeight: 600,
    color: COLORS.primary,
    letterSpacing: 3,
    marginBottom: 6,
  },
  elegantSubtitle: {
    fontSize: 10,
    color: COLORS.secondary,
    marginBottom: 28,
    textAlign: 'center',
  },
  elegantName: {
    fontSize: 20,
    fontWeight: 600,
    color: COLORS.dark,
    marginBottom: 12,
    textAlign: 'center',
  },
  elegantCourse: {
    fontSize: 13,
    color: COLORS.muted,
    marginBottom: 8,
  },
  elegantCourseName: {
    fontSize: 15,
    fontWeight: 600,
    color: COLORS.primary,
    marginBottom: 20,
    textAlign: 'center',
  },
  elegantFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 20,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.certGold,
  },
  elegantMeta: {
    fontSize: 9,
    color: COLORS.muted,
  },
  elegantExpiry: {
    fontSize: 9,
    color: COLORS.primary,
    marginTop: 10,
    textAlign: 'center',
    width: '100%',
  },
  elegantBadge: {
    borderWidth: 1,
    borderColor: COLORS.goldSoft,
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 18,
    marginBottom: 14,
    backgroundColor: COLORS.white,
  },
  elegantBadgeText: {
    fontSize: 8,
    color: COLORS.primary,
    fontWeight: 600,
    letterSpacing: 1.2,
    textAlign: 'center',
  },
  elegantQuote: {
    fontSize: 9,
    color: COLORS.muted,
    fontStyle: 'normal',
    textAlign: 'center',
    marginBottom: 18,
    maxWidth: 420,
    lineHeight: 1.5,
  },
  elegantRosetteTL: {
    position: 'absolute',
    top: 52,
    left: 52,
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1.25,
    borderColor: COLORS.certGold,
    opacity: 0.65,
    backgroundColor: COLORS.white,
  },
  elegantRosetteTR: {
    position: 'absolute',
    top: 52,
    right: 52,
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1.25,
    borderColor: COLORS.primary,
    opacity: 0.45,
    backgroundColor: COLORS.white,
  },
  elegantRosetteBL: {
    position: 'absolute',
    bottom: 52,
    left: 52,
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1.25,
    borderColor: COLORS.primary,
    opacity: 0.4,
    backgroundColor: COLORS.white,
  },
  elegantRosetteBR: {
    position: 'absolute',
    bottom: 52,
    right: 52,
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1.25,
    borderColor: COLORS.certGold,
    opacity: 0.55,
    backgroundColor: COLORS.white,
  },
  elegantBottomNote: {
    fontSize: 7,
    color: COLORS.muted,
    textAlign: 'center',
    marginTop: 12,
    letterSpacing: 0.3,
  },
});
export const DEFAULT_TAGLINE = 'Школа «AVATERRA» · мышечное тестирование';

export function taglineFor(data: CertificateData) {
  return (data.tagline && data.tagline.trim()) || DEFAULT_TAGLINE;
}

/** Светлый лист + диагональная сетка и контурные дуги (без крупных заливок) — заметнее и ровнее на печати. */
